### ISSUE TITLE
./renderer/rasterize_triangles_kernel_1.so could not find

### ISSUE THREAD

**Issue by Hong-Bo** [microsoft/DisentangledFaceGAN#1]
Hi, Great work first! Excited to execute the training script, but got stuck at the first step while running `python preprocess_data.py -h`. It gives the following error 
```
tensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel_1.so: cannot open shared object file: No such file or directory
```
when trying to load './renderer/rasterize_triangles_kernel_1.so' in `DisentangledFaceGAN/renderer/rasterize_triangles.py`, line 30. I guess this `.so` file was forgotten to upload by mistake.

**Comment by kanwangshijie** [comment]
hello,I meet the same problem,do you finally solve it?thanks.

**Comment by xi4444x** [comment]
Hi, I have the same question,can you tell me how to solve it?
