### ISSUE TITLE
no rotation in the data alignment procedure?

### ISSUE THREAD

**Issue by IQ17** [microsoft/DisentangledFaceGAN#10]
Hi, it seems that rotation is not considered in preprocess_data.py , do you assume that raw images are all corrected with 0 roll?

**Comment by YuDeng** [comment]
In our paper, we use FFHQ as training data which has 0 roll angle. However, this is not mandatory. You can use images with non-zero roll angles to train and obtain similar result. So we do not eliminate rotation in our data preprocessing.

**Comment by IQ17** [comment]
thanks!
