### ISSUE TITLE
Weird artifacts in generated images

### ISSUE THREAD

**Issue by onzone** [microsoft/DisentangledFaceGAN#13]
Hi, first of all, I would like to say you guys did an amazing work. So I was generating images with the code given and in some of the cases it's generating some weird artifact in the images(sometimes the skin is kind of cartoonish, the colours are out of the line or some patches over face).  I am not talking about extreme pose variation or illumination. So my question is , anyhow can we control such faces not to generate?

**Comment by YuDeng** [comment]
Hi, these artifact could occur at random. To avoid them, you can try to decrease the truncation rate(default is 0.7) as described in generate_image.py.  Artifacts should then reduced if not eliminated.

**Comment by onzone** [comment]
Thanks for your response. I have played with the truncation rate, but that didnt help much. :(
