### ISSUE TITLE
NotFoundError: ./renderer/rasterize_triangles_kernel_1.so

### ISSUE THREAD

**Issue by shreyanshdas00** [microsoft/DisentangledFaceGAN#16]
When trying to run the preprocess_data.py script i get the following error message:

> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "preprocess_data.py", line 12, in <module>
    from renderer import face_decoder
  File "./renderer/face_decoder.py", line 7, in <module>
    from renderer import mesh_renderer
  File "./renderer/mesh_renderer.py", line 25, in <module>
    from renderer import rasterize_triangles
  File "./renderer/rasterize_triangles.py", line 30, in <module>
    rasterize_triangles_module = tf.load_op_library('./renderer/rasterize_triangles_kernel_1.so')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./renderer/rasterize_triangles_kernel_1.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE

The environment is defined as per the guidelines mentioned in the repo. Any help would be appreciated. Thanks.

**Comment by Jackson-1102** [comment]
I have also met this problem,and this is about the match of environment.if you download the reconmended 'rasterize_triangles_kernel_1.so' in Google Drive ,and to use the tensorflow 1.12.0, this problem will disappear.
(Or you need to compile this file again in your own tensorflow environment)

**Comment by kanwangshijie** [comment]
I also encountered this problem, do you finally solve this problem?thanks

**Comment by kanwangshijie** [comment]
> I have also met this problem,and this is about the match of environment.if you download the reconmended 'rasterize_triangles_kernel_1.so' in Google Drive ,and to use the tensorflow 1.12.0, this problem will disappear.
> (Or you need to compile this file again in your own tensorflow environment)

My environment and .so is correct, but still report an error,is there anything else I need to pay attention to？thanks.

**Comment by xi4444x** [comment]
> > I have also met this problem,and this is about the match of environment.if you download the reconmended 'rasterize_triangles_kernel_1.so' in Google Drive ,and to use the tensorflow 1.12.0, this problem will disappear.
> > (Or you need to compile this file again in your own tensorflow environment)
> 
> My environment and .so is correct, but still report an error,is there anything else I need to pay attention to？thanks.

Me too, did you solve it? Looking forward to your reply.
