### ISSUE TITLE
What format are the pose angles encoded in gnerate_images.py?  

### ISSUE THREAD

**Issue by LeArmadillo** [microsoft/DisentangledFaceGAN#23]
What format are the angles give in latent[:,32+16:32+16+3].  They seem to range from +/- 0-3.14 as if they were in radians but the output does not match.  What format do you use to represent the angles?

**Comment by YuDeng** [comment]
Hi, the angles are three Euler angles w.r.t xyz axis. They are in radians.

**Comment by StelaBou** [comment]
Could you give more details for the correspondence between the last 3 dimension of the z vector and the angles?

I sampled 1000 images with -3 on yaw direction (last element on latent[:, 32+16:32+16+3]) and the predictions for yaw were approximately -60 degrees, so I assumed that  for yaw angle,  [-3, 3] on z vector corresponds to [-60, 60] degrees. 
I followed the same procedure for pitch and I assumed that [-3, 3] on z vector corresponds to [-25, 25] degrees. 
Am I right?

Thank you.

**Comment by YuDeng** [comment]
> Could you give more details for the correspondence between the last 3 dimension of the z vector and the angles?
> 
> I sampled 1000 images with -3 on yaw direction (last element on latent[:, 32+16:32+16+3]) and the predictions for yaw were approximately -60 degrees, so I assumed that for yaw angle, [-3, 3] on z vector corresponds to [-60, 60] degrees.
> I followed the same procedure for pitch and I assumed that [-3, 3] on z vector corresponds to [-25, 25] degrees.
> Am I right?
> 
> Thank you.

Hi, the absolute value in z space (latent space in VAE) is meaningless. In our method, only the value in lambda space (output space of VAE) has certain physical meaning.  And the last three dimensions in lambda space are Euler angles in radians. If you want to generate images with certain angles, it is better to give a specific angle value(in radians) directly in lambda space instead of in z space of VAE.

**Comment by StelaBou** [comment]
Could you tell me where in the code I can give a specific angle value directly in lambda ?
I was changing this latent code to take different angles https://github.com/microsoft/DiscoFaceGAN/blob/bf27d094776225b256d17de408171d8312271c27/generate_images.py#L194
Thank you.

**Comment by YuDeng** [comment]
You have to replace dimensions 224:227 of INPUTcoeff with a placeholder. These three dimensions correspond to Rotcoeff:
https://github.com/microsoft/DiscoFaceGAN/blob/bf27d094776225b256d17de408171d8312271c27/generate_images.py#L66
 Then you can send any angles you want (in radians) and generate face images with corresponding poses.
