### ISSUE TITLE
pre-trained model~

### ISSUE THREAD

**Issue by lss11005** [microsoft/DisentangledFaceGAN#3]
can you provide per-trained model in this project directly? I can't download it from google drive~
thank you so much

**Comment by YuDeng** [comment]
Hi，you can download the pre-trained model using this link: https://drive.google.com/file/d/1nT_cf610q5mxD_jACvV43w4SYBxsPUBq/view?usp=sharing

**Comment by YuDeng** [comment]
Hi, the model is a bit large to add to the repository directly. I provide an alternative link to download the pre-trained model:
link：https://pan.baidu.com/s/1iQqo5uvn2m-RQTu_eOLutg 
code：v045
Enter the code then you should be able to download the model.

**Comment by dniku** [comment]
@YuDeng could you re-upload the checkpoint to some storage that supports English interface?

**Comment by YuDeng** [comment]
> @YuDeng could you re-upload the checkpoint to some storage that supports English interface?

Hi, the google drive link for the pre-trained model has already been added to the test code. Is the link not work for you as well?

**Comment by dniku** [comment]
Sorry, I didn't notice that the link is included in the code.
