### ISSUE TITLE
Train the Stylegan generator with imitative-contrastive learning scheme

### ISSUE THREAD

**Issue by Young1403** [microsoft/DisentangledFaceGAN#30]
Thanks for your great work! I have a few questions:
1. How long time do you take to train stage1 and stage2?
2. The Stylegan generator  can be repalced by stylegan2?  Will stylegan2 be beneficial to this project?

**Comment by YuDeng** [comment]
Hi, you can check [here](https://github.com/microsoft/DiscoFaceGAN#training-networks) for the training time.

It is possible to replace stylegan with stylegan2. In that case, you don't need a progressive growing training strategy. We have conducted experiments on stage1 using the stylegan2, and the image quality measured by FID will be better than stylegan1.
