### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by naveengv7** [microsoft/DisentangledFaceGAN#33]
Hi,
While running python generate_images.py, the below error was encountered. Could you please help

Traceback (most recent call last):
  File "generate_images.py", line 199, in <module>
    main()
  File "generate_images.py", line 158, in main
    Gs = load_Gs(url_pretrained_model_ffhq)
  File "generate_images.py", line 136, in load_Gs
    _G, _D, Gs = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

Many thanks for considering my request.

**Comment by YuDeng** [comment]
Hi, can you try different version of python, e.g. python 3.6?

**Comment by naveengv7** [comment]
Hi,
Many thanks for the response. I've used python 3.6. But the same error persists. I guess it's a problem with the pre-trained pickle file. Kindly check.
Thank you.

**Comment by naveengv7** [comment]
I've manually downloaded the pkl file and provided it in code. Works fine. 
But the output of the generate_images.py looks like below. I've followed the instructions provided under "Testing with pre-trained network." I'm new to this; please help me here that what am I doing wrong here. 
Thank you

![000_00](https://user-images.githubusercontent.com/98863524/159765691-9ff8c8dd-0564-4fd0-ac0f-062dc4ecdb08.png)
![000_01](https://user-images.githubusercontent.com/98863524/159765693-14152689-c7cf-4305-94e6-418fa94c4b08.png)

**Comment by chunseng6800** [comment]
Hi naveengv7, do you might share the code for the solution?

**Comment by Eunjnnn** [comment]
I got same results,,,
How did you solve it?

**Comment by chinmayjog13** [comment]
any update on this? @naveengv7 ?

**Comment by fak111** [comment]
me too this 
![image](https://github.com/microsoft/DiscoFaceGAN/assets/97438502/65920440-9bf0-4925-8c2d-9f89df846956)
