### ISSUE TITLE
I'm implementing the image embedding in your paper, what am I doing wrong?

### ISSUE THREAD

**Issue by salfamusic** [microsoft/DisentangledFaceGAN#9]
Hey, so let me start by saying this is some impressive work! I've decided to take the challenge of implementing the image embedding + editing from your paper. I feel like I understand what I need to do, but I'm not getting good results. 

Let me say that I have the W+ state for an embedded image. I used the dataset you used in your code to do the embedding with the system provided by _Stylegan Encoder_ (https://github.com/Puzer/stylegan-encoder.git). It's in the shape of `[1, 14, 512]`, and I get the correct image out after running it through the synthesis function `Gs.components.synthesis.get_output_for(dlatents, randomize_noise = False)`.

So if I understand your paper and the Image2StyleGAN paper correctly, what I have is the W+ state of the image. According to your paper, I should be able to implement the following:

<img width="323" alt="Screen Shot 2020-07-04 at 1 28 56 PM" src="https://user-images.githubusercontent.com/47834713/86520692-d6bfcb00-be0c-11ea-8a94-2f0a2d9aaa94.png">

<img width="22" alt="Screen Shot 2020-07-04 at 3 47 14 PM" src="https://user-images.githubusercontent.com/47834713/86520760-a4629d80-be0d-11ea-85fa-ce53b24f6a95.png"> is the image I'm trying to encode

<img width="44" alt="Screen Shot 2020-07-04 at 3 47 51 PM" src="https://user-images.githubusercontent.com/47834713/86520772-b9d7c780-be0d-11ea-9e71-7fb99210cb9a.png"> was the process I went through to encode said image with _Stylegan Encoder_

<img width="38" alt="Screen Shot 2020-07-04 at 3 48 37 PM" src="https://user-images.githubusercontent.com/47834713/86520782-d542d280-be0d-11ea-92f4-6f968a50fe90.png">  is the `[1, 14, 512]` shape that I got from said _Stylegan Encoder_ process

<img width="49" alt="Screen Shot 2020-07-04 at 3 49 18 PM" src="https://user-images.githubusercontent.com/47834713/86520792-ed1a5680-be0d-11ea-919c-716ba2c64995.png"> is the `Gs.components.synthesis.get_output_for` func

and

<img width="99" alt="Screen Shot 2020-07-04 at 3 49 48 PM" src="https://user-images.githubusercontent.com/47834713/86520799-fe636300-be0d-11ea-8fc2-8097083f83de.png"> 
is equal to
<img width="284" alt="Screen Shot 2020-07-04 at 3 45 57 PM" src="https://user-images.githubusercontent.com/47834713/86520739-7715ef80-be0d-11ea-8bc8-74ac08f89735.png">

Now, for my implementation. I'm currently trying to manipulate one of the theta (ROT) variables. 

In order to do this I have hijacked the `truncate_generation` function. I felt it was the best spot to implement this.

Here is how I have implemented it:
```
def truncate_generation(Gs,inputcoeff,rate=0.7,dlatent_average_id=None):
    embedded_w_plus_space = np.reshape(np.load('embedded.npy'),[1,14,512]).astype(np.float32) # embedded image
    embedded_w_plus_space = tf.constant(embedded_w_plus_space)

    # INPUTcoeff = tf.concat([IDcoeff,EXPcoeff,Rotcoeff,GAMMAcoeff], axis = 1)
    # INPUTcoeff = tf.concat([INPUTcoeff, noise_], axis = 1)
    # final shape = [160, 64, 3, 27, 32]

    id_exp_zero = tf.zeros([1,160+64])
    rand_rot_isolate = tf.concat([inputcoeff[:,160+64:160+64+1], tf.zeros([1, 2])], axis=1)
    gamma_noise_zero = tf.zeros([1,27+32])

    lambda_i_equals_a = tf.concat([id_exp_zero, rand_rot_isolate, gamma_noise_zero],axis=1)
    lambda_i_equals_b = lambda_i_equals_a * 0.0

    w_i_equals_a = Gs.components.mapping.get_output_for(lambda_i_equals_a, None ,is_training=False, is_validation = True)
    w_i_equals_b = Gs.components.mapping.get_output_for(lambda_i_equals_b, None ,is_training=False, is_validation = True)

    delta_w_iab = w_i_equals_a - w_i_equals_b #w(a) - w(b)

    x_t_pre_synth = embedded_w_plus_space + delta_w_iab

    x_t = Gs.components.synthesis.get_output_for(x_t_pre_synth, randomize_noise = False)
    x_t = tf.clip_by_value((x_t+1)*127.5,0,255)
    x_t = tf.transpose(x_t,perm = [0,2,3,1])

    return x_t 
```

Am I on the right track? Can you give me some hints? Thanks! Let me know if you want me to explain anything further.

**Comment by YuDeng** [comment]
Hi, your understanding of each component is correct. 

However, it might not be a good choice to use zero identity coefficient and zero noise as input to Gs.components.mapping because the network can hardly receive such input during the training process. You can give the generator zero identity/noise to see what image is generated. In my experiment, it leads to poor generation results. 

As a result, you can use a reasonable identity coefficient (identity extracted from 3D reconstruction network) and a random noise sampled from normal distribution to replace the zero input. It should give you a better editing result. 

BTW, can you post your editing results here so maybe I can figure out what is going wrong?

**Comment by salfamusic** [comment]
YuDeng, 

Thanks for the quick reply! Sorry I didn't get back to you yesterday, I had a flight to catch and no internet to reply. 

Good point on the zero identity and noise coefficients. 

So I have replaced the Identity coefficient with the result from random normal distribution run through the z_to_lambda function (this is how you are generating random identities in the source code). I do this with the assumption the resulting lambda latents are reasonable. I also used the random normal distributed noise.

Okay, so in order to better run tests, I have put the code that does the bulk of building x_t into its own method to allow for rapid testing.

```
def build_x_t_pre_synth(Gs, embedded_w_plus_space, id_lambda, exp_lambda, gamma_lambda, noise_lambda, rot_lambda_a, rot_lambda_b):
  lambda_i_equals_a = tf.concat([id_lambda, exp_lambda, rot_lambda_a, gamma_lambda, noise_lambda],axis=1)
  lambda_i_equals_b = tf.concat([id_lambda, exp_lambda, rot_lambda_b, gamma_lambda, noise_lambda],axis=1)

  w_i_equals_a = Gs.components.mapping.get_output_for(lambda_i_equals_a, None ,is_training=False, is_validation = True)
  w_i_equals_b = Gs.components.mapping.get_output_for(lambda_i_equals_b, None ,is_training=False, is_validation = True)

  delta_w_iab = w_i_equals_a - w_i_equals_b #w(a) - w(b)

  x_t_pre_synth = embedded_w_plus_space + delta_w_iab

  return x_t_pre_synth
```

I've then split out the piece that does the synthesis into its own method. This returns an object with the network as well as the name I assign it. (This is for easy file naming).

```
def produce_res(Gs, latent, name):
  network_out = Gs.components.synthesis.get_output_for(latent, randomize_noise = False)
  network_out = tf.clip_by_value((network_out+1)*127.5,0,255)
  network_out = tf.transpose(network_out,perm = [0,2,3,1])

  return {
      'network': network_out,
      'name': name
  }
```

And finally the guts (similar to method from previous post)

```
def run_edit_tests(Gs,inputcoeff,rate=0.7,dlatent_average_id=None):
  embedded_w_plus_space = np.reshape(np.load('musk_01.npy'),[1,14,512]).astype(np.float32) # embedded image
  embedded_w_plus_space = tf.constant(embedded_w_plus_space)

  # INPUTcoeff = tf.concat([IDcoeff,EXPcoeff,Rotcoeff,GAMMAcoeff], axis = 1)
  # INPUTcoeff = tf.concat([INPUTcoeff, noise_], axis = 1)
  # final shape = [160, 64, 3, 27, 32]

  id_from_coeff = inputcoeff[:,:160]
  exp_from_coeff = inputcoeff[:, 160: 160+64]
  gamma_from_coeff = inputcoeff[:, 160+64+3: 160+64+3+27]
  noise_from_coeff = inputcoeff[:, 160+64+3+27:]

  exp_zero = tf.zeros([1, 64])
  gamma_zero = tf.zeros([1, 27])

  # rot_a should end up being [0.2, 0.0, 0.0]
  rot_a = tf.concat([tf.ones([1, 1]) * 0.2, tf.zeros([1, 2])], axis=1)

  # rot_b should end up being [0.0, 0.0, 0.0]
  rot_b = tf.zeros([1, 3])

  # prepare test using zeros for expression and gamma
  x_t_test1 = build_x_t_pre_synth(
      Gs = Gs,
      embedded_w_plus_space = embedded_w_plus_space,
      id_lambda = id_from_coeff,
      exp_lambda = exp_zero,
      gamma_lambda = gamma_zero,
      noise_lambda = noise_from_coeff,
      rot_lambda_a = rot_a,
      rot_lambda_b = rot_b
  )

  # prepare test using values from coefficient for expression and gamma
  x_t_test2 = build_x_t_pre_synth(
      Gs = Gs,
      embedded_w_plus_space = embedded_w_plus_space,
      id_lambda = id_from_coeff,
      exp_lambda = exp_from_coeff,
      gamma_lambda = gamma_from_coeff,
      noise_lambda = noise_from_coeff,
      rot_lambda_a = rot_a,
      rot_lambda_b = rot_b
  )

  results = [] 

  # prepare the original as well as the two tests for rendering
  results.append(produce_res(Gs, embedded_w_plus_space, 'original'))
  results.append(produce_res(Gs, x_t_test1, 'test1'))
  results.append(produce_res(Gs, x_t_test2, 'test2'))

  # results are then iterated through, and saved with the name I ran them with
  return results 
```

I ran 2 tests. One using the zero expression and zero gamma, and the other using the expression and gamma from the coefficient passed in.

Here are the resulting images. 

ORIGINAL
![original](https://user-images.githubusercontent.com/47834713/86628739-efa4b980-bf8f-11ea-85a1-2ab0d785ab39.png)

TEST 1
![test1](https://user-images.githubusercontent.com/47834713/86628768-f9c6b800-bf8f-11ea-8383-d48757d60498.png)

TEST 2
![test2](https://user-images.githubusercontent.com/47834713/86628816-0ea34b80-bf90-11ea-977d-d700b410176b.png)


I'm afraid that the mistake is in the encoding (it's perhaps not high enough quality? Or I'm doing something wrong). 

Here are the dlatents I used. (change extension to .npy)
[musk_01.txt](https://github.com/microsoft/DisentangledFaceGAN/files/4880753/musk_01.txt)

Let me know what you think. Thanks!

**Comment by salfamusic** [comment]
I just had a realization. I'm going to guess that the alignment of these images is incorrect (I'm using the alignment from the encoder project). I'm going to try and align them using your preprocess_data.py then encode them. If you think this isn't worth the time, and I should try something else, let me know.

**Comment by salfamusic** [comment]
I just used the `preprocess_data.py` script to align the image. It didn't work, in fact the results were worse. 

However, I did notice that the aligned image that it produced seemed to consistently offset the face to the left. Perhaps I am doing something wrong?

Here's an example:

Before alignment
![musk](https://user-images.githubusercontent.com/47834713/86667276-17f3de80-bfb7-11ea-80ab-d4839e576352.png)

After alignment
![musk (1)](https://user-images.githubusercontent.com/47834713/86667562-60130100-bfb7-11ea-9aaf-5833c9f9153b.png)

Like I said, this skewing to the left result is consistent.

**Comment by salfamusic** [comment]
Ah, I just realized that you require center of left eye, center of right eye, nose, left mouth, and right mouth as the 5 points. 

Just an FYI dlib doesn't give you back those 5 points. They give left of left eye, right of left eye, left of right eye, right of right eye and bottom of nose.

MTCNN gives the correct results.

I'm going to implement MTCNN and see if the results are better.

**Comment by salfamusic** [comment]
We are sooo close!! 

Using MTCNN definitely improved the alignment. However, I just found in the code how I can get the 5 points from the 68 points that dlib returns.

In the function `load_lm3d()` you do the work for translating this. Here's a snippet with a comment I added

```
# calculate 5 facial landmarks using 68 landmarks
lm_idx = np.array([31,37,40,43,46,49,55]) - 1

# nose, left eye, right eye, left mouth, right mouth
Lm3D = np.stack([Lm3D[lm_idx[0],:],np.mean(Lm3D[lm_idx[[1,2]],:],0),np.mean(Lm3D[lm_idx[[3,4]],:],0),Lm3D[lm_idx[5],:],Lm3D[lm_idx[6],:]], axis = 0)
Lm3D = Lm3D[[1,2,0,3,4],:]
```

Anyway. Back to the matter at hand. Here is the aligned image of Elon Musk:

![musk_01](https://user-images.githubusercontent.com/47834713/86683181-eaaf2c80-bfc6-11ea-9628-e4dfef1ce4db.png)

This is much better.

The embedded version of this image looks like this:

![original (1)](https://user-images.githubusercontent.com/47834713/86684856-8db47600-bfc8-11ea-9c59-c66544aec928.png)


And using the following code (very similar to the code above, just some slight tweaks)

```
def run_edit_tests(Gs,inputcoeff,rate=0.7,dlatent_average_id=None):
  embedded_w_plus_space = np.reshape(np.load('1_musk.npy'),[1,14,512]).astype(np.float32) # embedded image
  embedded_w_plus_space = tf.constant(embedded_w_plus_space)

  # INPUTcoeff = tf.concat([IDcoeff,EXPcoeff,Rotcoeff,GAMMAcoeff], axis = 1)
  # INPUTcoeff = tf.concat([INPUTcoeff, noise_], axis = 1)
  # final shape = [160, 64, 3, 27, 32]
  
  id_from_coeff = inputcoeff[:,:160]
  exp_from_coeff = inputcoeff[:, 160: 160+64]
  rot_from_coeff = inputcoeff[:, 160+64: 160+64+3]
  gamma_from_coeff = inputcoeff[:, 160+64+3: 160+64+3+27]
  noise_from_coeff = inputcoeff[:, 160+64+3+27:]

  exp_zero = tf.zeros([1, 64])
  gamma_zero = tf.zeros([1, 27])

  # rot_a should end up being [0.1, 0.0, 0.0]
  rot_a = tf.concat([tf.ones([1, 1]) * 0.1, tf.zeros([1, 2])], axis=1)

  # rot_b should end up being [0.0, 0.0, 0.0]
  rot_b = tf.concat([tf.ones([1, 1]) * 0.0, tf.zeros([1, 2])], axis=1)

  # prepare test
  x_t_test1 = build_x_t_pre_synth(
      Gs = Gs,
      embedded_w_plus_space = embedded_w_plus_space,
      id_lambda = id_from_coeff,
      exp_lambda = exp_zero,
      gamma_lambda = gamma_zero,
      noise_lambda = noise_from_coeff,
      rot_lambda_a = rot_a,
      rot_lambda_b = rot_b
  )

  # prepare test reversing rot_a and rot_b
  x_t_test2 = build_x_t_pre_synth(
      Gs = Gs,
      embedded_w_plus_space = embedded_w_plus_space,
      id_lambda = id_from_coeff,
      exp_lambda = exp_zero,
      gamma_lambda = gamma_zero,
      noise_lambda = noise_from_coeff,
      rot_lambda_a = rot_b,
      rot_lambda_b = rot_a
  )

  # prepare test swapping rot_from_coeff out for rot_a
  x_t_test3 = build_x_t_pre_synth(
      Gs = Gs,
      embedded_w_plus_space = embedded_w_plus_space,
      id_lambda = id_from_coeff,
      exp_lambda = exp_zero,
      gamma_lambda = gamma_zero,
      noise_lambda = noise_from_coeff,
      rot_lambda_a = rot_from_coeff,
      rot_lambda_b = rot_b
  )

  results = [] 

  # prepare the original as well as the two tests for rendering
  results.append(produce_res(Gs, embedded_w_plus_space, 'original'))
  results.append(produce_res(Gs, x_t_test1, 'test1'))
  results.append(produce_res(Gs, x_t_test2, 'test2'))
  results.append(produce_res(Gs, x_t_test3, 'test3'))

  # results are then iterated through, and saved with the name I ran them with
  return results 
```

Here are the three results:

TEST 1: rot [0.1, 0.0, 0.0] - [0.0, 0.0, 0.0]
![test2 (1)](https://user-images.githubusercontent.com/47834713/86684900-960cb100-bfc8-11ea-97b9-5ccc27dd79ef.png)

TEST 2: rot [0.0, 0.0, 0.0] - [0.1, 0.0, 0.0]
![test1 (2)](https://user-images.githubusercontent.com/47834713/86686287-d6b8fa00-bfc9-11ea-86b6-c1f656419769.png)

TEST 3: rot from generated coeff (included below) - [0.0, 0.0, 0.0]
![test3](https://user-images.githubusercontent.com/47834713/86688366-a4100100-bfcb-11ea-9f91-e020bfa18534.png)


THIS IS SO CLOSEE!!! Amazing. I'm still going to strive for better results however!

Just so you can follow along/ try it out yourself - 

Here are the latent weights for the embedding of Elon Musk (change extension to .npy):
[1_musk.txt](https://github.com/microsoft/DisentangledFaceGAN/files/4881984/1_musk.txt)

As for what's being passed in as the `inputcoeff` variable in the `run_edit_tests`.. here are the z coefficients I'm using prior to transformation to the lambda space (change extension to .npy):
[lats.txt](https://github.com/microsoft/DisentangledFaceGAN/files/4882056/lats.txt)


Here are the next few things I'm going to try to get improved results

1. Use dlib 68 landmarks and translate them to 5
2. Mimic FFHQ's image preparation process on image of Elon Musk
3. Retrain image embedding network on your network
4. Let the embedding process run longer (I'm currently letting it run for 10000 iterations and the loss is for the image above got down to 0.29)
4. Keep problem solving

As always, please chime in with any tips or advice or help!


P.S. In my fork I'm automatically generating the 5 landmarks, so I'm going to be making a PR soon that allows the user an option to have the 5 landmarks be generated automatically

**Comment by salfamusic** [comment]
Good news! 

I switched to a different encoder and it works PHENOMENALLY!!! I will post my results tomorrow.

You did an amazing job writing this paper and building the system! Congratulations.

**Comment by salfamusic** [comment]
Well here are the results. Like I said, this is incredible.

The solution was switching to the following encoder https://github.com/rolux/stylegan-encoder

ORIGINAL
![original (2)](https://user-images.githubusercontent.com/47834713/86803690-d5c0b080-c03b-11ea-917c-f117eb9c2d78.png)

TEST 1
![test1 (3)](https://user-images.githubusercontent.com/47834713/86803712-dbb69180-c03b-11ea-996c-16020b47820a.png)

TEST 2
![test2 (2)](https://user-images.githubusercontent.com/47834713/86803725-de18eb80-c03b-11ea-801a-847a168c2605.png)

TEST 3 A
![test3 (1)](https://user-images.githubusercontent.com/47834713/86803766-e7a25380-c03b-11ea-88f5-05bdf555fb71.png)

**Comment by YuDeng** [comment]
Hi, thanks a lot for your effort to the image embedding and editing task. The result obtained by using the new encoder seems reasonable. 
It is quite interesting to use an encoder for embedding. In our paper, we do not train an encoder to get latent code from images. Instead, we directly update the latent code for an image through backprop.  Directly optimizing the latent code for each image can better preserve the attributes of the original image and may give you a better editing result.

**Comment by salfamusic** [comment]
Yu Deng,

I have noticed the limitations of using an encoder. I would like to give the method you recommend a try. Can you give me some guidance or direction as to what I should do next?

Is there a paper/repository you can direct me to? Or perhaps could you provide a description of the backprop process?

**Comment by YuDeng** [comment]
The backprop process is simple. We use a similar method as in (Image2StyleGAN)[https://arxiv.org/abs/1904.03189]. We start from an average latent vector in W+ space (1x14x512), where the average vector is calculated from 50k random samples. We use the latent vector as the input to the generator and obtain a generated image. By comparing the L2 loss and perceptual loss between the generated image and the real image which we intend to embed, the gradient can be backprop to the input latent vector in W+ space and we directly update it using an Adam optimizer. Finally, after around 3000 iterations, we obtain the final embedding vector we want.

**Comment by zachlewis** [comment]
(Thanks, both of you -- this thread has been really helpful for me!)

**Comment by renmengyuan** [comment]
> following encoder https://github.com/rolux/stylegan-encoder


> Well here are the results. Like I said, this is incredible.
> 
> The solution was switching to the following encoder https://github.com/rolux/stylegan-encoder
> 
> ORIGINAL
> ![original (2)](https://user-images.githubusercontent.com/47834713/86803690-d5c0b080-c03b-11ea-917c-f117eb9c2d78.png)
> 
> TEST 1
> ![test1 (3)](https://user-images.githubusercontent.com/47834713/86803712-dbb69180-c03b-11ea-996c-16020b47820a.png)
> 
> TEST 2
> ![test2 (2)](https://user-images.githubusercontent.com/47834713/86803725-de18eb80-c03b-11ea-801a-847a168c2605.png)
> 
> TEST 3 A
> ![test3 (1)](https://user-images.githubusercontent.com/47834713/86803766-e7a25380-c03b-11ea-88f5-05bdf555fb71.png)

Hi, the latent vector dimension of stylegan encoder(https://github.com/rolux/stylegan-encoder) is 18*512, but the dimension is 14*512 in DiscoGan, how did you deal with it.

**Comment by renmengyuan** [comment]
@salfamusic 
Hi, the latent vector dimension of stylegan encoder(https://github.com/rolux/stylegan-encoder) is 18512, but the dimension is 14512 in DiscoGan, how did you deal with it.

**Comment by renmengyuan** [comment]
> Yu Deng,
> 
> I have noticed the limitations of using an encoder. I would like to give the method you recommend a try. Can you give me some guidance or direction as to what I should do next?
> 
> Is there a paper/repository you can direct me to? Or perhaps could you provide a description of the backprop process?

@salfamusic Hi, the latend vector dimension in stylegan(https://github.com/rolux/stylegan-encoder) is 18*512, but 14*512 in DiscoGan, how did you deal with it? Is there is a pretrained model which is 256*256 size not 1024*1024 size.

**Comment by voyager0003** [comment]
lol, what if musk see those photos

**Comment by lychenyoko** [comment]
> Yu Deng,
> 
> I have noticed the limitations of using an encoder. I would like to give the method you recommend a try. Can you give me some guidance or direction as to what I should do next?
> 
> Is there a paper/repository you can direct me to? Or perhaps could you provide a description of the backprop process?

Hi, 

I am just wondering if you could share your codes on real image editing with DiscoFaceGAN. Thanks in advance!
